name = "syrsacraft"
author = "BamsyTheSergal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "69b2670d3cd57715a27884ebf31e33b9e1e8bba45deaabfd520b90444b7ad3d8"

[versions]
forge = "40.1.80"
minecraft = "1.18.2"
