name = "syrsacraft"
author = "BamsyTheSergal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cee35b88d1786ba014f166b83ab3f94328f4d553aad790d0042f140253552209"

[versions]
forge = "40.1.80"
minecraft = "1.18.2"
