name = "syrsacraft"
author = "BamsyTheSergal"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c60b46a45474eab1b798c527b6e3e0b9dd233d9a02711ed3aaed754df06ca7cd"

[versions]
forge = "40.1.80"
minecraft = "1.18.2"
